-- Migration: Add mind_map JSONB column to gravacoes
-- This stores the auto-generated mind map for each lecture recording.
-- The column is nullable — if generation fails, it's simply NULL and iOS hides the mind map tab.
-- Generated by the mind_map_service in the same background task as the summary.

ALTER TABLE gravacoes 
ADD COLUMN IF NOT EXISTS mind_map JSONB DEFAULT NULL;

-- Add a comment for documentation
COMMENT ON COLUMN gravacoes.mind_map IS 
'Auto-generated mind map JSON. Schema: { topic: string, branches: [{ topic, color (0-3), children: [string, string, string] }] }. Always 4 branches x 3 children. NULL if generation failed or pending.';
